export const {
    CREATE_TEXT,
    ERROR_MESSAGE_FS,
    FRESH_TXT,
    SUCCESS,
    ERROR_MESSAGE,
    TEST_FOULED,
    TEST,
    TEST_CONTENT,
    FOLDER_NAME,
} = {
    FRESH_TXT: 'fresh.txt',
    CREATE_TEXT: 'I am fresh and young',
    ERROR_MESSAGE_FS: 'FS operation failed',
    SUCCESS: 'success',
    ERROR_MESSAGE: 'Ops.. error',
    TEST_FOULED: 'test fouled',
    TEST: 'test',
    TEST_CONTENT: 'test content',
    FOLDER_NAME: 'test_folder',
} as const;